### PR TITLE
Make sure user account exists before using single-signon

### PR DESCRIPTION
**Pull request by mattboehm**
If the user's CKAN account has not been created, they must log in
normally. Without checking for this, users without accounts would be in
a state where they were half-logged-in and many site features would
break.

### CODE REVIEW

**Comment by tanderegg** [comment]
@mattboehm Is it possible to include logic within the SSO code to create the account if it doesn't exist?  Or do we need to have them login manually in order to get information required to create the account?  If possible it would be nice not to require the manual login, but let me know if that is not feasible.

**Comment by mattboehm** [comment]
@tanderegg I think the following code would do it:

    from ckanext.ldap.controllers.user import _find_ldap_user, _get_or_create_ldap_user
    _get_or_create_ldap_user(_find_ldap_user(login))

The main issue is testing the code: I'd need to find a person who's never logged in and ask them to log into staging for me or ask an admin to delete an account on staging then get that user to log in.

Because we're using "private" methods, it's always possible that future ckanext-ldap plugins break this code, but they don't seem to update their code that often anyway.

**Comment by tanderegg** [comment]
@mattboehm I'm sure we can test it, if you implement the change I will find a proper guinea pig and give it a try, thanks!

**Comment by mattboehm** [comment]
@tanderegg I fixed the issue and had an office mate test it on staging. Everything looks good.

**Pull request merged**
