### PR TITLE
CSV export

### PR DESCRIPTION
**Pull request by mattboehm**
Add a plugin to export a list of all datasets as CSV.

Currently only supports public datasets (we need to upgrade CKAN to 2.4+ before we can include private datasets.)

To test:

* pull this branch
* re-install this repo (so that the new plugin is registered)
* add `ckanext_cfpb_export` to `cfpb.plugins` in `config.ini`
* restart apache
* click on the "Datasets" tab in the data catalog
* click the "Export CSV" link to the right of the breadcrumbs

### CODE REVIEW

**Comment by mattboehm** [comment]
Let me know if having this many git commits bugs you. This mostly happened because I using git to move code between computers while developing and am happy to rebase this into fewer commits if folks would prefer that.

**Comment by tanderegg** [comment]
@mattboehm A rebase would probably be a good idea, I've had to do this myself many times for the same reason :)  Also, looks like the Travis build failed on an import error, but I don't know whether or not that was the result of an pre-existing problem.

**Comment by mattboehm** [comment]
@tanderegg Actually, that was a result of the tests ultimately depending on ckan/ckanapi to be installed. I've now refactored that code into files not required by the unit tests and travis is passing again.

**Comment by mattboehm** [comment]
Made a separate PR for the rebased branch: #30

**Pull request closed without merging**
