### PR TITLE
Add plugin to query ldap

### PR DESCRIPTION
**Pull request by mattboehm**
Adds a page where you can query for the members of any LDAP group.

Depends on https://github.com/NaturalHistoryMuseum/ckanext-ldap/pull/17

### CODE REVIEW

**Comment by mattboehm** [comment]
@tanderegg I had to make the following change to ckan-installer to switch it to my branch: https://github.com/mattboehm/ckan-installer/pull/2 

If my ckanext-ldap PR is accepted, this will be a moot point, but otherwise I'll have to merge this into my mesos-rebase branch on ckan-installer.

**Comment by tanderegg** [comment]
@mattboehm This is great, although what I was originally thinking is that a admin user could do this from the same page where the access roles were listed. In other words, in addition to the "role" and "desc" fields, there would be a "group" field that contains the relevant Active Directory group related to that role. Then, an admin user could click on that role to see who the members are. Ultimately, we could do the reverse as well - allow a user to visit a page where they see every resource they have access to. Would that be doable?

(I accidentally commented on the Natural History PR, then deleted it, if you saw random emails, sorry!)

**Comment by mattboehm** [comment]
Ah, I was thinking of "role" as being the group field and envisioned the same workflow that you do. Another thing to consider is if we'd ever want the user to specify an alternative OU in a field. This means that there are up to 4 potential fields per entry:

* LDAP OU
* LDAP CN
* Short name for the role
* Longer description of the role

We could simplify things by combining name/description as I'd assumed and/or by either not having an OK field or combining it with the CN field (expecting the user to enter `<alternate_ou>/<group_cn>` or something).

It should be fairly straightforward to add a page that would show all groups a member is in. We may want to filter out some entries from this list, though.

**Comment by tanderegg** [comment]
I think we can set the OU's at the app level, right now there are only two that may contain the groups, so we could just try one, and then the other if the first fails.  Is that workable?  The CN is always the group name, so I was thinking it would be Role Name, Role CN, and Role Description.  This is because the group names follow certain conventions that could be confusing, although the Role Name might not be necessary if the Description is clear enough.

For the lookup page, I was thinking a step more complex: basically retrieve a user's groups, then match them against the contents of the Data Catalog and only return resources where there is a match between a Role CN and the group name.  That way a user could see all the specific dataset info, and not see groups that are not related to datasets.  Basically use the LDAP group CN as a foreign key between a user and Data Catalog resources.

Thanks!

**Comment by tanderegg** [comment]
@mattboehm Looks like this was has overlap with #49, I'll wait until that one is merged, and this one is rebased, then review.

**Comment by tanderegg** [comment]
@mattboehm Are you still planning to rebase this or is it good to merge, thanks!

**Comment by mattboehm** [comment]
@tanderegg good to merge; merged master in with commit 00044be instead of rebasing this branch on top of it.

**Pull request merged**
