### PR TITLE
Fix labels for exported fields

### PR DESCRIPTION
**Pull request by mattboehm**

### CODE REVIEW

**Review by JeffreyMFarley — COMMENTED** [review]
Just an FYI, I've been getting notes from the design team that the style guide prefers Sentence case over Title Case

So it should be `Initial size (MB)`

**Comment by mattboehm** [comment]
@JeffreyMFarley Thanks. We added a ticket to the backlog to fix the casing of everything in the Data Catalog as there are plenty of inconsistencies. I'll add a comment that sentence casing is preferred.

**Comment by tanderegg** [comment]
@mattboehm Do we want to update this PR to use sentence casing before merge?

**Comment by mattboehm** [comment]
@tanderegg fixed and ready to merge.

**Pull request merged**
